# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 703534fcd5a962e41c5ae0fcfc0fd760cc77fd53229e034306c6ae54c2f0a6ca6170ba7e5271826d28b91ae78829a90435585c6ae3f2ffcbe15d5d25d4169bd8

test:
  secret_key_base: 02de6f113e663e447ee936b1aeb7e4007081daa2a142cc682d172b3677c3f26ef5f5b8b31e87af9fa0b5cbd4df31d57d23166234e586e922c0e79e8e688e7552

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
